### ISSUE TITLE
No sohkd in root directory

### ISSUE THREAD

**Issue by zywek123** [odilia-app/odilia#105]
Hello.
I discovered this project and want to try it.
First thing, you don't have to run it as root, will be enough to add your user to the odilia group and install as a regular user. Odilia does not want to start as root, because of no at-spi daemon detected.
Second thing, I can't locate sohkd to properly use shortcuts assigned to Odilia. I don't have it in my main repository directory of the odilia project. Where i can retrieve it?

**Comment by jcaesar** [comment]
> The readme no longer contains references to sohkd or permissions... 

Huh?

https://github.com/odilia-app/odilia/blob/a06ab246b6de96cd4cebea82bad17ee4ef2f1245/README.md?plain=1#L47-L54

**Comment by TTWNO** [comment]
Oh shoor! I missed that one!

I removed a few references, I'll remove this one as well.

**Comment by TTWNO** [comment]
Odilai should not run with root privilege, since it won't be able to attach to the accessibility session. Is there a reason you are wanting to run Odilia as root?

**Comment by zywek123** [comment]
Look at readme, and something about /etc config locations.

**Comment by TTWNO** [comment]
All of that should be removed now as well. This was mentioned by somebody else on a Reddit post :)

**Comment by zywek123** [comment]
OK, so only one question.  Someone use irc or this channel should be closed?

**Comment by TTWNO** [comment]
I beleive the channel is still active, if that's what you're asking. It should be bridged to our Matrix server.

**Comment by zywek123** [comment]
Great.
