### ISSUE TITLE
Org contributions

### ISSUE THREAD

**Issue by Shinyzenith** [odilia-app/odilia#14]
Odilia looks like a very interesting project! Although I'm not a visually impaired linux user, I would like to help out as I believe that accessibility is a huge gap that we need to bridge in our community. 

If anyone could point me to a todo list, I'd love to try and contribute.

Sincerely,
Aakash Sen Sharma

**Comment by TTWNO** [comment]
Hey! We'd love contributuons!

Since you're already supporting us through the `swhkd` crate, I'd love some help with input. This is my primary focus. The other two main contributers handle most of everything else.

Currently, our adaption of the code supports Option<Key> for keysym, with capslock as a modifier instead of a key. This is so `capslock + b/a/o` can be used for switching modes (think like Vim modes, but for interacting with your screen reader).

I'm super jazzed about your involvement! I'd gladly explain anything you need. We're working on better documentation as we speak, but I'd love to fill in any gaps.

Thanks again! Can't wait for a PR 👍

**Comment by TTWNO** [comment]
Feel free to join our Matrix channel if you want.

Join my space Odilia Screen Reader https://matrix.to/#/#odilia-screen-reader:matrix.org

**Comment by TTWNO** [comment]
Oh I forgot to mention what you could help me with.

It would be nice if we could get the reversed key problems fixed. I mentioned it in the thread on `swhkd` but I'll mention it here again:

If I have a keybinding `capslock+f` and I type f + capslock, then capslock gets passed through to the window manager, my caps gets turned on and the f key is tepeatedly typed by the input daemon.

Can't quite figure out why this is. Any help would be greatly appreciated.

**Comment by Shinyzenith** [comment]
On Mon Aug 15, 2022 at 11:30 AM IST, Tait Hoyem wrote:

> Since you're already supporting us through the `swhkd` crate, I'd love some help with input. This is my primary focus. The other two main contributers handle most of everything else.

Perfect, I'll try and help out with sohkd.

> Currently, our adaption of the code supports Option<Key> for keysym, with capslock as a modifier instead of a key. This is so `capslock + b/a/o` can be used for switching modes (think like Vim modes, but for interacting with your screen reader).
Ok so caps should be treated as modifier, I'll get on it asap.

**Comment by Shinyzenith** [comment]
On Mon Aug 15, 2022 at 11:33 AM IST, Tait Hoyem wrote:
> Feel free to join our Matrix channel if you want.
>
> Join my space Odilia Screen Reader https://matrix.to/#/#odilia-screen-reader:matrix.org

Done!

**Comment by Shinyzenith** [comment]
On Mon Aug 15, 2022 at 10:11 PM IST, Tait Hoyem wrote:
> It would be nice if we could get the reversed key problems fixed. I mentioned it in the thread on `swhkd` but I'll mention it here again:
>
> If I have a keybinding `capslock+f` and I type f + capslock, then capslock gets passed through to the window manager, my caps gets turned on and the f key is tepeatedly typed by the input daemon.
I haven't been able to reproduce this yet. I will investigate this.

**Comment by TTWNO** [comment]
Just going to close this issue, but so far your contributions have been invaluable and I hope we can continue to collaborate through the `swhkd` project.
