### ISSUE TITLE
Can't compile. "can't find crate for `zvariant_derive`"

### ISSUE THREAD

**Issue by tete-github** [odilia-app/odilia#155]
Hello I'm trying to build from source as outlined here: https://odilia.app/doc/user/installation/

On an immutable SteamOS 3.5.19 , with Rust 1.80.0 from the Rustup site.

I get the following errors:
[build.txt](https://github.com/user-attachments/files/17268752/build.txt)

I tried to add zvariant_derive = "4.1.1" to the Cargo.toml ,
I looked up this issue on zbus repo - https://github.com/dbus2/zbus/issues?q=is%3Aissue+zvariant_derive+is%3Aopen
to no avail.

What am I missing here, how to proceed?😭

**Comment by TTWNO** [comment]
We require Rust 1.81
