### ISSUE TITLE
Stop Speech on Exit

### ISSUE THREAD

**Issue by mcb2003** [odilia-app/odilia#16]
Currently when quitting Odilia, speech-dispatcher will continue to say whatever Odilia was speaking at the time. Instead, we should catch the exit signals (`SIGINT`, `SIGQUIT`, `SIGTERM`, possibly `SIGHUP`, etc), stop speech, then exit as normal. Tokio has the [`tokio::signal`](https://docs.rs/tokio/latest/tokio/signal/index.html) module for that.

**Comment by TTWNO** [comment]
Fixed by commit `cd79b27347b58b3aa7f9ed04b24ae2e871e0ad2e`
