### ISSUE TITLE
Publish the atspi crate

### ISSUE THREAD

**Issue by DataTriny** [odilia-app/odilia#22]
Hey there, this project looks great!
I would need AT-SPI's client-side types to test our server-side implementation for [AccessKit](https://github.com/accesskit/accesskit).
I'd like to avoid duplicating efforts. Do you plan to release the atspi crate contained in this repository in a near future? Can I help to push this forward?
Thanks in advance.

**Comment by TTWNO** [comment]
I plan on doing this soon, yes. I'm moving this week, but the AT-SPI crate has been fairly stable for some time now. I'll add a couple small methods and change some of the traits to be in line with Rust's standards (*Plus -> *Ext). I can very likely get this out in under a month. Does that work for you?

You are welcome to make a few of those changes, or add any features you would like to see as a PR before I publish `atspi 0.1.0`, like I said, probably later this month. I'll make sure to @ you once it's public, if you'd like?

Glad to see our crates are being used outside of this project! :)

**Comment by TTWNO** [comment]
Well, there were less changes required than I thought, so I've published the `atspi` crate as is with version 0.0.1

Let me know if there's anything missing and we'll be sure to add it in a more stable version.

**Comment by DataTriny** [comment]
Thanks @TTWNO for the quick response. I'll start replacing my own types and start collaborating here as I find missing pieces.
