### ISSUE TITLE
Consider Relicensing `atspi`

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/odilia#34]
Currently, @DataTriny is working on using our `atspi` crate for the AccessKit suite of tools.
These tools are licensed under Apache 2.0, MIT, and BSD licenses, which are incompatible with the GPL (in that direction).

Although we currently license atspi with the LGPL, this is somewhat problematic with Rust, where you don't link libraries together like you do in C.
I wish there was a license similar to the LGPL for Rust, but there really isn't.

So I propose three options:

* Keep it the same. This could restrict usage, but from the GNU standpoint, that's a good thing.
* Relicense under the MPL, a file-based copy-left license. So technically they could add files to add functionality without sharing changes, but realistically that's probably not going to happen.
* Relicense as the Rust-standard MIT or Apache 2.0; this would allow the crate to be used in propietary products *with* modifications. The upside is thst it will massively increase adoption since it can be used in a project with any license. So does MPL, but since it's not as popular, it may scare some off even though that has the benefit of sharing modifications.

I'm not going to give my own opinion here for now, just want to see what others think. We'll probably need consent from everyone involved to relicense, so I'll have to see what @mcb2003 thinks as well. We never really talked about how to license individual, separate components, and Rust complicates things with its package management.

Thoughts?

**Comment by DataTriny** [comment]
I feel entitled to speak here since I have contributed to this project, so here is my take:

While I am ideologically in favor of GPL for a software like Odilia, I don't think LGPL is a good idea for a Rust crate. As @TTWNO pointed out, LGPL would legally prevent me from using it within AccessKit, as Rust statically links crate dependencies.

If the end goal is to have accessibility everywhere (and I think we all agree on this here), then imposing a license barrier is unproductive.

Initially AccessKit was BSD licensed, but we switched to MIT/Apache 2.0 early on, since it was the best option for us. Now, only certain files are still covered by the BSD license, as their content is strongly inspired by Chromium.

I would be fine with MPL, but my vote goes towards MIT/Apache 2.0 dual licensing.

**Comment by albertotirla** [comment]
damn it, I don't understand why github won't let me reply via email, however I agree with the MIT approach as well, it's not odilia specific.

**Comment by TTWNO** [comment]
Ok, I only need an opinion from @mcb2003 

I'm fine with MIT/Apache since it's rhe Rust standard and allows our library to be used by anything which wishes to be accessible.

I agree with DataTriny, Odilia should certainly be GPL, but for a Rust library, LGPL doesn't really make sense.

**Comment by albertotirla** [comment]
isn't lgpl about any kind of linking though? Technically, static linking is still linking, however it's performed in another way, so lgpl should be applicable there as well? If it mentions dynamic linking by name though, then we have a problem. Yes, I do agree with the MIT/apache for this, however consider this question as something to help us decide future licensing matters.

**Comment by TTWNO** [comment]
I'll open a discussion about broader licensing. This'll just be for atspi.

**Comment by albertotirla** [comment]
in that case, we're only waiting on @mcb2003 and then we can decide

**Comment by TTWNO** [comment]
@mcb2003  has confirmed he's fine we the relicense in the following comment: https://matrix.to/#/!BVPeWFRhpOwtjxKvET:matrix.org/$5qSA9bGyvl86ZTZ2zQ5yUPyafGC70mbgLdFGIXozOw4?via=matrix.tait.tech&via=t2bot.io&via=matrix.org

Quote here:

> I don't have any time at all to hang around, because I'm trying my best to catch up with a bunch of work this weekend, but just so you know, **I'm okay with the relicense of at-spi**, and I don't like the idea of multiple speech backends because I think we need to push people to write speech-dispatcher modules so it becomes a quasi standard for all Linux TTS synths and applications.
