### ISSUE TITLE
`serde` version for the `atspi` crate

### ISSUE THREAD

**Issue by DataTriny** [odilia-app/odilia#38]
Is there a reason why the `serde` dependency of the `atspi` crate is explicitly set to `1.0.136`?

Today I tried adding my fork of the `atspi` crate to my AccessKit Linux adapter to start the migration, but I can't even compile since in our workspace we use `serde` version `1.0` and cargo can't find a suitable version that satisfies everyone.

If technically possible, would you agree to depend on `serde`, version `1.0`, as recommended by the project authors?

I can send a PR if you want.

**Comment by TTWNO** [comment]
Shouldn't be a problem. I'll fix that ASAP.

**Comment by DataTriny** [comment]
Thanks @TTWNO ,

I can now compile. I'll start the migration then.
