### ISSUE TITLE
Qt Applications Do NOT Work

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/odilia#7]
According to [the following comment](https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/main/xml/Event.xml#L4), the Event.xml file in the atspi library is *not* correct.

Because of this, Odilia can currently only receive events from GTK applications; Qt applications use a different event signature which errors out the `zbus` crate with "Invalid signature" errors.

This is not a bug in DBus, Odilia, GTK or Qt. `atspi` is currently allowing multiple signature types for events; this needs to be standardized at the library level, and we should be happy to help.
I personally know nothing of GTK, Qt, or DBus code itself, but if atspi needs some fixing, I'm sure either I or @mcb2003 should be able to take a gander.

Once this is stabilized library-side, Odilia should immediately work with Qt applications, with no further modifications necessary. :+1:

**Comment by TTWNO** [comment]
Now, instead of Odilia failing to receive QT events, as soon as the event is received, the QT application crashes outright. Both `vlc` and `virtualbox` (QT applications) seg-faulted straight-up.

**Comment by TTWNO** [comment]
Confirmed that calling the GetName or GetDescriptiom method causes a segfault.

**Comment by TTWNO** [comment]
https://bugreports.qt.io/browse/QTBUG-107897

**Comment by DataTriny** [comment]
Hi @TTWNO ,
What happens here is that by default, zbus proxies use [`CacheProperties::Lazily`](https://docs.rs/zbus/latest/zbus/enum.CacheProperties.html).

This means that when you handle a focus event and fetch the `Name` property of the accessible object, zbus will under the hood send a `GetAll` method call on the `org.freedesktop.DBus.Properties` interface to populate the cache. However, Qt (like at-spi2-core) don't implement this method. It's just that at-spi2-core doesn't crash.

If I modify the `accessible::new` function in the `atspi` crate to tell the proxy to not cache properties, the bug disappear.

```
pub async fn new<'a>(
    conn: &Connection,
    sender: UniqueName<'_>,
    path: ObjectPath<'_>,
) -> zbus::Result<AccessibleProxy<'a>> {
    AccessibleProxy::builder(conn)
        .destination(sender.to_owned())?
        .path(path.to_owned())?
        .cache_properties(CacheProperties::No) // Disable the caching mechanism.
        .build()
        .await
}
```

A quick look at the entire odilia source code makes me think that there are probably a ton of other places where you'd have to apply this modification.

Let me know if I can assist.

Hope this helps.

**Comment by TTWNO** [comment]
Wow! Great find! I never even noticed that this was the problem.

Based on what you are saying, is it the case that `GetAll` is also not implemented in GTK either (I guess if `at-spi2-core` doesn't implement it, then GTK couldn't either....) This is a really bummer for performance, but a good thing to be aware of.

I'll test out this fix on the weekend and make sure it works. If this really does solve this issue, you're a saint for finding the underlying problem!

I'm going to continue with the upstream QT bug so that at least the program doesn't segfault on this DBus call, but hopefully this can close the Odikia bug sooner rather than later.

Again, great find!

**Comment by DataTriny** [comment]
@TTWNO 

Oh sorry, by saying "at-spi2-core doesn't implement this method", I also meant that at-spi2-atk didn't either. Therefore, GTK3, Chromium, and basically every other software don't. I doubt GTK4 is any different.

Note that AccessKit will support this call because we use zbus `ObjectServer`, but I think that it's more efficient to use the dedicated `org.a11y.atspi.Cache` interface anyway.
