### ISSUE TITLE
UX: inconvenient way to start odilia

### ISSUE THREAD

**Issue by albertotirla** [odilia-app/odilia#78]
# problem

currently, the way in which odilia has to be launched is very inconvenient for the end user, since it usually involves two terminals and most likely at least one password prompt, depending if you're configuring it for the first time. I understand this is mostly because of sohkd, but this considerably raises the barier to entry for new users and contributors alike

Here's a quick rundown of what a new user would have to do to get odilia to run properly, taken from the current readme and adapted for markdown rendering:

* clone the repo and cd into it
* build the program: `cargo build --release`
* run this command as root, it will give yourself access to evdev and such: `sudo ./scripts/setup_permissions.sh`
  * note: is this still necesary, see below
* install the config files needed for odilia or sohkd to not panic: `sudo ./scripts/install_configs.sh`
  * why do this as root? why do we install configs in /etc at all?
* build sohkd: `cd sohkd && cargo build --release`
  * why isn't sohkd built with odilia and placed in the same directory with it?
* start odilia:
```
./scripts/odilia
# in another terminal
./scripts/debug_start_sohkd.sh
```
* type your password when required

now, odilia is hopefully started, but that took, a lot of steps, any of which could be wrong and cause mostly cryptic and unhelpful error messages. Actually, what inspired me to make this issue was my failure to do the above steps correctly, when prepairing a new linux box for odilia development. The UX is so convoluted, if I didn't read the readme which I didn't for a time, I would have failed, I did that a lot

# solution

the simplest checklist I could come up with is the following:

- [ ] don't use configuration from /etc, keep it user scoped or make sane defaults when config files aren't present, removes the need for the install configs script to be run as root, if at all
- [ ] remove the setup-permissions.sh script, I guess it's no longer required since users are prompted for passwords when started sohkd
- [ ] make odilia build sohkd so that both binaries are in the same output folder

an even simpler alternative would be for us to make odilia incorporate the functionality of sohkd, that way we won't have these issues again, but I guess we don't want that for the longterm and that's why we don't incorporate it.

**Comment by TTWNO** [comment]
> an even simpler alternative would be for us to make odilia incorporate the functionality of sohkd,

Incorporating key events through DBus/xdg/wayland-protocols should be coming soon thanks to Matt Campbell, Mike Gorse, so I'm not going to put any further effort into sohkd. It should be obsolete in the next few months.

**Comment by albertotirla** [comment]
> > an even simpler alternative would be for us to make odilia incorporate the functionality of sohkd,
> 
> Incorporating key events through DBus/xdg/wayland-protocols should be coming soon thanks to Matt Campbell, Mike Gorse, so I'm not going to put any further effort into sohkd. It should be obsolete in the next few months.

I mean, probably, on wayland, on a few desktops, maybe with two wide or two narrow permission scopes, but what about x11, what about other desktops than gnome, what if we want to implement a narrower permissions scope in order to further restrict what we or addons have access to? I think sohkd isn't going away for a while, so I wouldn't be so quick to dismiss it. I think we would find the desktop portal somehow either lacking, designed with two few usecases in mind, or implemented by not enough wayland compositors, so if not using a daemon process, perhaps we'd have to use a library or something to further restrict access. Thinking about the fact x11 is still prevalent in the blind linux community because mate is the most accessible desktop, we have to support that for a while as well. Just saying, try using any current desktop that supports wayland with only orca and nothing else, you'll quickly find out more work is required. While that work is done, people are still using x, so unfortunately we can't do anything but support that too.

**Comment by TTWNO** [comment]
If there is a standard way to do it, then we will not continue the maintainence burden of having our own key handler. The only reason we have this right now is because Wayland does not support the current standard for implementing AT key bindings.

If you want Odilia to incorporate sohkd, that's something I'd need a PR for, since I don't personally think it's necessary, but it might be ok as a stop-gap solution if you want to put your time into it.

**Comment by albertotirla** [comment]
because I already did some work on this to the point the UX isn't so bad anymore, also since sohkd will probably go away soon enough and would be replaced by the input crate which may contain both a wayland and an x11 solution, I'm closing this as solved, feel free to reopen if there are pertinent points to still discuss on this matter.
