### ISSUE TITLE
UX: structural navigation keys don't work

### ISSUE THREAD

**Issue by albertotirla** [odilia-app/odilia#79]
# problem description

after starting odilia, browse mode and focus mode keys don't emit any feedback, spoken or otherwise, neither does trying to use any of the navigation keys listed in the configuration files

# steps to reproduce

1. Configure odilia if required
2. start odilia, as described in the readme
3. open a web browser known to be accessible to screenreaders, such as firefox
4. try going in browse mode, you'll see it does not work
5. try pressing any of the quick navigation keys, for example h, shift+h, l, i, etc. Similarly, you'll discover it does not work

# expected behavior

keystrokes should work. For example, h in browse mode should move me through headings, while odilia+b in focus mode should move me to browse mode

**Comment by albertotirla** [comment]
perhaps related to #6 in some way, some modifications may have been done during that time which rendered structural navigation unusable?

**Comment by TTWNO** [comment]
capslock + b is the browse mode key combo. And Odilia currently does not notify you of modr changes. This works on my computer, so I wonder if the config files aren't being installed correctly.

**Comment by albertotirla** [comment]
what do you do to make it work? I pressed capslock+b multiple times, with no luck. Also, hopefully you're using it with orca turned off, otherwise orca can move you through headings even when odilia is active.
